# -*- coding: utf-8 -*-
"""iphone sales analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1914ppYvh9xfpHCDj1tIvUSItYZrqNlaK
"""

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# import dataset

data =pd.read_csv('/content/apple_products.csv')

data.head()

data.isnull().sum()

data.describe()

data.head()

## Higest iphone sales in india now i will create new dataframe  ,all the data about top 10 higesht rated


highest_rated = data.sort_values(by=["Star Rating"],ascending=False)

highest_rated= highest_rated.head(10)

highest_rated['Product Name']

highest_rated

from google.colab import drive
drive.mount('/content/drive')

## Now let's have looks n of the rating of the highest rated iphone on flipkart


iphones=highest_rated["Product Name"].value_counts()
label = iphones.index
counts=highest_rated["Number Of Ratings"]
fig = px.bar(highest_rated, x=label, y=counts, title="Number of Ratings of Highest Rated Iphones")
fig.show()

## Now let's have looks n of the Reviews of the highest rated iphone on flipkart


iphones=highest_rated["Product Name"].value_counts()
label = iphones.index
counts=highest_rated["Number Of Reviews"]
fig = px.bar(highest_rated, x=label, y=counts, title="Number of Reviews of Highest Rated Iphones")
fig.show()

## Now relation between sales price of iphone or their rating on flipkart


fig=px.scatter(data_frame=data, x="Number Of Ratings", y="Sale Price",size="Discount Percentage",trendline="ols",
               title="Relationship between Sale Price And Number of Ratings")
fig.show()

## Now relation between discont percentage or number of rating


fig=px.scatter(data_frame=data, x="Number Of Ratings", y="Discount Percentage",size="Sale Price",trendline="ols",
               title="Relationship between Discount percetage And Number of Ratings")
fig.show()

## Diffn betn expensivie or least expensive

most_expensive =data.loc[data['Sale Price'].idxmax()]

least_expensive =data.loc[data['Sale Price'].idxmin()]


print("Most Expensice product:")
print(most_expensive)
print("\nLeast Expensice product:")
print(least_expensive)